all:
  children:
    proxmox:
      vars:
        ansible_user: root
      hosts:
        proxmox-1:
          ansible_host: 192.168.10.11
        proxmox-2:
          ansible_host: 192.168.10.12
        proxmox-3:
          ansible_host: 192.168.10.13
